# Generated by Django 4.2.4 on 2023-08-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='data_finish',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='data_start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
    ]
