# Generated by Django 4.2.4 on 2023-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_id_schedule_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
