# Generated by Django 4.2.4 on 2023-08-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_schedule_id_task_schedule_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_start',
            field=models.DateTimeField(null=True),
        ),
    ]
