# Generated by Django 4.2.4 on 2023-09-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
